In [ ]:
import numpy as np

In [ ]:
from sklearn.datasets import load_iris
iris = (load_iris())

In [ ]:
type(iris)

sklearn.utils.Bunch

In [ ]:
print(iris.DESCR)
print(iris.data)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
from keras.utils import to_categorical

In [ ]:
X=iris.data
y = iris.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
y = to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
y.shape

(150, 3)

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
#need to standardize or normalize the inout.example of normalization.Here divide by the max value


In [ ]:
np.array([5,10,15,20])/20

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
scaler_object = MinMaxScaler()

In [ ]:
scaler_object.fit(X_train)
# we only  fit to train and use of test.we don't want to cheat and use for test data
scaled_X_train = scaler_object.transform(X_train)

In [ ]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

Build model using keras


In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(8,input_dim =4,activation='relu'))
model.add(Dense(8,input_dim =4,activation='relu'))
model.add(Dense(3,activation = 'softmax'))

In [ ]:
#get ouput softmax in terms of probabilities

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)
#verbose is how much progress you want  to see when you  run this cell

Epoch 1/150
4/4 - 0s - loss: 1.1631 - accuracy: 0.3100
Epoch 2/150
4/4 - 0s - loss: 1.1505 - accuracy: 0.3100
Epoch 3/150
4/4 - 0s - loss: 1.1403 - accuracy: 0.3100
Epoch 4/150
4/4 - 0s - loss: 1.1301 - accuracy: 0.3200
Epoch 5/150
4/4 - 0s - loss: 1.1216 - accuracy: 0.3200
Epoch 6/150
4/4 - 0s - loss: 1.1122 - accuracy: 0.3200
Epoch 7/150
4/4 - 0s - loss: 1.1038 - accuracy: 0.3300
Epoch 8/150
4/4 - 0s - loss: 1.0959 - accuracy: 0.3200
Epoch 9/150
4/4 - 0s - loss: 1.0891 - accuracy: 0.3800
Epoch 10/150
4/4 - 0s - loss: 1.0826 - accuracy: 0.4400
Epoch 11/150
4/4 - 0s - loss: 1.0772 - accuracy: 0.4500
Epoch 12/150
4/4 - 0s - loss: 1.0710 - accuracy: 0.5100
Epoch 13/150
4/4 - 0s - loss: 1.0654 - accuracy: 0.5800
Epoch 14/150
4/4 - 0s - loss: 1.0605 - accuracy: 0.6400
Epoch 15/150
4/4 - 0s - loss: 1.0554 - accuracy: 0.7200
Epoch 16/150
4/4 - 0s - loss: 1.0501 - accuracy: 0.7100
Epoch 17/150
4/4 - 0s - loss: 1.0460 - accuracy: 0.6300
Epoch 18/150
4/4 - 0s - loss: 1.0405 - accuracy: 0.4600
E

In [ ]:
# scale test data as well, because our model is trauined on the scale model

In [ ]:
scaled_X_test = scaler_object.transform(X_test)
model.predict(scaled_X_test)

array([[0.02841837, 0.5483821 , 0.42319945],
       [0.9418348 , 0.02772119, 0.03044411],
       [0.00266753, 0.35550052, 0.641832  ],
       [0.03859771, 0.5017744 , 0.45962796],
       [0.01617172, 0.47360125, 0.5102271 ],
       [0.89735353, 0.05286838, 0.04977811],
       [0.10820996, 0.51593643, 0.37585366],
       [0.01429078, 0.3202379 , 0.6654713 ],
       [0.01894772, 0.52769715, 0.45335516],
       [0.0570562 , 0.55952716, 0.38341665],
       [0.0222002 , 0.38598713, 0.5918127 ],
       [0.84514093, 0.08593891, 0.06892011],
       [0.93410826, 0.03132014, 0.03457166],
       [0.8622885 , 0.07559261, 0.06211895],
       [0.9505525 , 0.02162061, 0.02782675],
       [0.04130732, 0.45219085, 0.50650185],
       [0.01020369, 0.35811225, 0.63168406],
       [0.05316206, 0.5929285 , 0.35390937],
       [0.04289652, 0.55274975, 0.40435374],
       [0.01147481, 0.37914884, 0.6093764 ],
       [0.8687359 , 0.07052428, 0.06073983],
       [0.02873394, 0.4468693 , 0.5243967 ],
       [0.

In [ ]:
# to have output in terms of classes
predictions = model.predict_classes(scaled_X_test)

In [ ]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0,  8,  7],
       [ 0,  0, 16]])

In [ ]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.53      0.70        15
           2       0.70      1.00      0.82        16

    accuracy                           0.86        50
   macro avg       0.90      0.84      0.84        50
weighted avg       0.90      0.86      0.85        50



In [ ]:
print(accuracy_score(y_test.argmax(axis=1),predictions))

0.86


for really large network, we need to save and load our model

In [ ]:
model.save('myfirst.h5')

In [ ]:
# now import this model.
# be careful to run the cell saved model again because it will overwrite

In [ ]:
from keras.models import load_model

In [ ]:
new_model = load_model('myfisrt.h5')

OSError: ignored